# Generated by Django 4.1.7 on 2023-03-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pctdata',
            name='filled_countrypy',
        ),
        migrations.AddField(
            model_name='pctdata',
            name='filled_country',
            field=models.CharField(default='WOW', help_text='The country code where the patent was filed in the PCT database.', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pctdata',
            name='pct_id',
            field=models.CharField(default='69', help_text='The ID of the patent in the PCT database.', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pctdata',
            name='published_or_filled_date',
            field=models.DateField(help_text='The date when the patent was published or filled by the office.'),
        ),
    ]
