# Generated by Django 4.1.7 on 2023-03-17 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_filled_country_pctdata_filed_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pctdata',
            name='application_number',
        ),
    ]
