# Generated by Django 4.1.7 on 2023-03-17 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_pctdata_application_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pctdata',
            name='patent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='pct_date', serialize=False, to='main.patent'),
        ),
    ]
