# Generated by Django 4.1.7 on 2023-03-17 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_pctdata_patent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PCTData',
        ),
    ]
