# Generated by Django 4.1.7 on 2023-03-17 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_pctdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCTData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pct_id', models.CharField(help_text='The ID of the patent in the PCT database.', max_length=100)),
                ('published_or_filed_date', models.DateField(help_text='The date when the patent was published or filed by the office.')),
                ('filed_country', models.CharField(help_text='The country code where the patent was filed in the PCT database.', max_length=100)),
                ('granted', models.BooleanField(help_text="Whether the patent is published and granted or it's just filed.")),
                ('patent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pct_date', to='main.patent')),
            ],
        ),
    ]
