# Generated by Django 4.1.7 on 2023-03-17 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_pctdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignee',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignees', to='main.location'),
        ),
        migrations.AlterField(
            model_name='inventor',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventors', to='main.location'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='withdrawn',
            field=models.BooleanField(help_text="Whether the patent has been withdrawn, in other words if it hasn't lost its validity."),
        ),
        migrations.AlterField(
            model_name='pctdata',
            name='patent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pct_data', to='main.patent'),
        ),
    ]
