# Generated by Django 4.1.7 on 2023-03-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_assignee_location_alter_inventor_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignee',
            name='first_name',
            field=models.CharField(blank=True, help_text='The first name of the assignee if the assignee is an individual.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assignee',
            name='last_name',
            field=models.CharField(blank=True, help_text='The last name of the assignee if the assignee is an individual.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventor',
            name='first_name',
            field=models.CharField(blank=True, help_text='The first name of the inventor.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventor',
            name='last_name',
            field=models.CharField(blank=True, help_text='The last name of the inventor.', max_length=100, null=True),
        ),
    ]
