# Generated by Django 4.1.7 on 2023-03-29 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_assignee_first_name_alter_assignee_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patentcitation',
            name='citation_date',
            field=models.DateField(help_text='The date when the patent was cited.', null=True),
        ),
        migrations.AlterField(
            model_name='patentcitation',
            name='cited_patent_country',
            field=models.CharField(help_text="The country code of the cited patent if it's not in the database.", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patentcitation',
            name='citing_patent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citations', to='main.patent'),
        ),
        migrations.AlterField(
            model_name='patentcitation',
            name='record_name',
            field=models.CharField(blank=True, help_text='The name of the record.', max_length=150, null=True),
        ),
    ]
